import pandas as pd

# 读取 Excel 文件
file_path =  "/data/cjk/project/wjc/dj_synth_challenge/output/eval_results/MGM-2B-Finetune-final_not_pre_1e6_8e7/mmbench/answers_upload/mmbench_dev_20230712/MGM-2B-Finetune-final_not_pre_1e6_8e7.xlsx"
df = pd.read_excel(file_path)

# 统计预测与真实答案相同和不同的数量
correct_predictions = (df['prediction'] == df['answer']).sum()
incorrect_predictions = (df['prediction'] != df['answer']).sum()

# 打印结果
print(f"预测正确的数量_0822_222K_48K_48K: {correct_predictions}")
print(f"预测错误的数量_0822_222K_48K_48K: {incorrect_predictions}")


#[2024-09-04 03:47:29,927] [INFO] [runner.py:570:main] cmd = /data/cjk/miniconda3/envs/dj2/bin/python -u -m deepspeed.launcher.launch --world_info=eyJsb2NhbGhvc3QiOiBbNCwgNSwgNiwgN119 --master_addr=127.0.0.1 --master_port=12351 --enable_each_rank_log=None /data/cjk/project/wjc/dj_synth_challenge/toolkit/training/mgm/train/train_mem.py --deepspeed /data/cjk/project/wjc/dj_synth_challenge/toolkit/training/scripts/zero2_offload.json --model_name_or_path /data/cjk/project/wjc/dj_synth_challenge/toolkit/training/model_zoo/LLM/gemma/gemma-2b-it --version gemma --data_path ../input/pretrain_stage_1/0904_mgm_pretrain_stage_1_matching_recall_240k.jsonl-200k.jsonl.json --image_folder ../input/pretrain_stage_1 --vision_tower /data/cjk/project/wjc/dj_synth_challenge/toolkit/training/model_zoo/OpenAI/clip-vit-large-patch14-336 --vision_tower_aux /data/cjk/project/wjc/dj_synth_challenge/toolkit/training/model_zoo/OpenAI/openclip-convnext-large-d-320-laion2B-s29B-b131K-ft-soup --mm_projector_type mlp2x_gelu --tune_mm_mlp_adapter True --mm_vision_select_layer -2 --mm_use_im_start_end False --mm_use_im_patch_token False --image_size_aux 768 --bf16 True --output_dir /data/cjk/project/wjc/dj_synth_challenge/toolkit/../output/training_dirs/MGM-2B-Pretrain-0904_mgm_pretrain_stage_1_matching_recall_240k_100_2 --num_train_epochs 1 --per_device_train_batch_size 8 --per_device_eval_batch_size 4 --gradient_accumulation_steps 8 --evaluation_strategy no --save_strategy steps --save_steps 100 --save_total_limit 1 --learning_rate 1e-3 --weight_decay 0. --warmup_ratio 0.03 --lr_scheduler_type cosine --logging_steps 50 --tf32 True --model_max_length 2048 --gradient_checkpointing True --dataloader_num_workers 4 --lazy_preprocess True --report_to none

#[2024-09-04 12:53:51,699] [INFO] [runner.py:570:main] cmd = /data/cjk/miniconda3/envs/dj2/bin/python -u -m deepspeed.launcher.launch --world_info=eyJsb2NhbGhvc3QiOiBbMCwgMSwgMiwgM119 --master_addr=127.0.0.1 --master_port=12358 --enable_each_rank_log=None /data/cjk/project/wjc/dj_synth_challenge/toolkit/training/mgm/train/train_mem.py --deepspeed /data/cjk/project/wjc/dj_synth_challenge/toolkit/training/scripts/zero2_offload.json --model_name_or_path /data/cjk/project/wjc/dj_synth_challenge/toolkit/training/model_zoo/LLM/gemma/gemma-2b-it --version gemma --data_path ../input/pretrain_stage_1/0904_mgm_pretrain_stage_1_matching_recall_240k.jsonl-200k.jsonl.json --image_folder ../input/pretrain_stage_1 --vision_tower /data/cjk/project/wjc/dj_synth_challenge/toolkit/training/model_zoo/OpenAI/clip-vit-large-patch14-336 --vision_tower_aux /data/cjk/project/wjc/dj_synth_challenge/toolkit/training/model_zoo/OpenAI/openclip-convnext-large-d-320-laion2B-s29B-b131K-ft-soup --mm_projector_type mlp2x_gelu --tune_mm_mlp_adapter True --mm_vision_select_layer -2 --mm_use_im_start_end False --mm_use_im_patch_token False --image_size_aux 768 --bf16 True --output_dir /data/cjk/project/wjc/dj_synth_challenge/toolkit/../output/training_dirs/MGM-2B-Pretrain-0904_mgm_pretrain_stage_1_matching_recall_240k_100_4 --num_train_epochs 1 --per_device_train_batch_size 8 --per_device_eval_batch_size 4 --gradient_accumulation_steps 8 --evaluation_strategy no --save_strategy steps --save_steps 100 --save_total_limit 1 --learning_rate 1e-3 --weight_decay 0. --warmup_ratio 0.03 --lr_scheduler_type cosine --logging_steps 50 --tf32 True --model_max_length 2048 --gradient_checkpointing True --dataloader_num_workers 4 --lazy_preprocess True --report_to none
